{
    'name': 'POS Custom UI',
    'version': '1.0.0',
    'category': 'Point of Sale',
    'summary': 'Custom POS UI product language fields',
    'depends': ['point_of_sale', 'pos_self_order', 'pos_restaurant'],
    'assets': {
        'point_of_sale._assets_pos': [
            'pos_custom_ui/static/src/app/components/category_selector/category_selector.js',
            'pos_custom_ui/static/src/app/screens/product_screen/actionpad_widget/actionpad_widget.js',
            'pos_custom_ui/static/src/app/screens/product_screen/product_screen.xml',
            'pos_custom_ui/static/src/app/screens/product_screen/product_screen.scss',
            (
                'after',
                'pos_restaurant/static/src/app/screens/product_screen/control_buttons/control_buttons.xml',
                'pos_custom_ui/static/src/app/screens/product_screen/control_buttons/control_buttons.xml',
            ),
            'pos_custom_ui/static/src/app/utils/printer/generate_printer_data.js',
            'pos_custom_ui/static/src/app/components/popups/combo_configurator_popup/combo_configurator_popup.js',
            'pos_custom_ui/static/src/app/components/product_card/product_card.xml',
            'pos_custom_ui/static/src/app/components/product_card/product_card.scss',
            'pos_custom_ui/static/src/app/components/orderline/orderline.xml',
        ],
        'pos_self_order.assets': [
            'pos_custom_ui/static/src/app/services/disable_indexeddb.js',
            'pos_custom_ui/static/src/app/pages/combo_page/combo_page.js',
            'pos_custom_ui/static/src/app/pages/product_list_page/product_list_page.js',
            'pos_custom_ui/static/src/app/pages/product_page/product_page.js',
            'pos_custom_ui/static/src/app/pages/product_page/product_page.xml',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'application': False,
}